### ISSUE TITLE
Allow configurable regex normalization

### ISSUE THREAD

**Issue by noqcks** [xeol-io/xeol#271]
**What would you like to be added**:

Related to https://github.com/xeol-io/xeol/issues/269

Managing a list of regex's for all potential package version strings is likely to become really tedious.
Instead of hard coding all the regex's, perhaps expose this list in config.yaml as a way to append more patterns to the list in normalizeSemver().

```
match:
  packages:
    regex:
      - '^(\d+\.\d+\.\d+)p\d+'
      - '^(\d+\.\d+\.\d+)-\d+~\w+'
```
